---
- name: Render operator specified list of configs
  include_tasks: "common/config/config_block.yml"
  register: "registered_configs"
  with_items: "{{ consul_configs }}"
  loop_control:
    loop_var: cfg
  tags:
    - config

- name: Scan supplied configs for specification of data_dir
  command: "grep -q 'data_dir' {{ item.path|default(config_dir) }}/{{ item.name }}.json"
  register: _datadir_scans
  ignore_errors: yes
  check_mode: no
  changed_when: no
  with_items: "{{ consul_configs }}"
  tags:
    - config

- name: Flag whether data_dir setting has been found
  set_fact:
    _datadir_set: true
  with_items: "{{ _datadir_scans.results }}"
  when: item.rc == 0
  tags:
    - config

- name: Assert data_dir flag is True
  assert:
    that: _datadir_set
  tags:
    - config
